defaults:
  - commons
  - _self_

name: colormnist_ood
loader:
    _target_: src.data.datasets.colormnist.ColorMNISTDataset
    val_size: 0.1
    ftune_size: 0.      # 0.3
    ftune_val_size: 0.  # 0.1
    coloring:
        train:
            mode: custom    #False / random / custom
            kwargs:
                mode: "single values"    
                values: [1,3,5,7,9] # parameter to manage the color in the custom rule: 
                                  # if digit in custom_digits color = "red", "green" otherwise
                                  # after preprocessing: 0 = red, 1 = green
        test:
            mode: custom    #False / random / custom
            kwargs:
                mode: "single values"    
                values: [0,2,4,6,8] # parameter to manage the color in the custom rule: 
                                  # if digit in custom_digits color = "red", "green" otherwise
                                  # after preprocessing: 0 = red, 1 = green

batch_size: 512

is_image_dataset: true
reduce_fraction: Null
onehot_to_concepts: true

load_embeddings: true

label_descriptions:
    number: "a variable representing a number from 0 to 9."
    parity: "a categorical variable that classifies each number based on its parity. It takes one of two values, 'even' (1) or 'odd' (0), where 'even' refers to numbers divisible by 2."
    color: "a binary variable indicating a color, taking one of two possible values: 'red' (1) or 'green' (0)."