defaults:
  - commons
  - _self_

name: sachs
loader:
    _target_: src.data.datasets.bndataset.BNDataset
    dag_name: sachs
    task_name: Akt
    dataset_n_samples: 10000
    val_size: 0.1 # 10% of total dataset
    test_size: 0.2
    ftune_size: 0.      
    ftune_val_size: 0.  
    bias:
        train:
            mode: false   #False / custom
            kwargs: {}
        test:
            mode: false
            kwargs: {}

autoencoder:
  noise: 0.
  latent_dim: 32
  lr: 0.0005
  epochs: 2000
  batch_size: 512
  patience: 50

is_image_dataset: false
reduce_fraction: Null
onehot_to_concepts: false

label_descriptions:
  Akt: "(protein kinase B) A serine/threonine-specific protein kinase involved in multiple cellular processes such as glucose metabolism, apoptosis, and cell proliferation. Measured as continuous activation levels."
  Erk: "(extracellular signal-regulated kinase) A kinase involved in the MAPK signaling pathway, crucial for cell division, differentiation, and survival. Measured as continuous activation levels."
  Jnk: "(c-Jun N-terminal kinase) A kinase involved in stress signaling pathways that regulate apoptosis, inflammation, and cytokine production. Measured as continuous activation levels."
  P38: "(p38 mitogen-activated protein kinase) A kinase involved in cellular responses to stress and inflammation. Measured as continuous activation levels."
  Mek: "(MAPK/ERK kinase) An upstream activator of ERK, involved in signal transduction for growth and survival. Measured as continuous activation levels."
  PKC: "(protein kinase C) A family of protein kinases involved in controlling the function of other proteins, regulating various cellular processes. Measured as continuous activation levels."
  PKA: "(protein kinase A) A kinase regulated by cyclic AMP, playing a key role in metabolism, gene transcription, and cell survival. Measured as continuous activation levels."
  Raf: "(RAF kinase) An upstream regulator of the MEK/ERK pathway, important in cell proliferation and differentiation. Measured as continuous activation levels."
  Plcg: "(phospholipase C gamma) An enzyme involved in the phosphoinositide signaling pathway, critical for cell proliferation and differentiation. Measured as continuous activation levels."
  PIP2: "(phosphatidylinositol 4,5-bisphosphate) A precursor molecule in the phosphoinositide signaling pathway, hydrolyzed to produce DAG and IP3. Measured as continuous concentration levels."
  PIP3: "(phosphatidylinositol 3,4,5-trisphosphate) A lipid signaling molecule produced by PI3K, critical for cell growth and survival. Measured as continuous concentration levels."
