_target_: "src.models.c2bm.C2BM"
hidden_size: 64
concept_hidden_size: 8
n_layers_encoder: 1
n_layers_concept_encoder: 1
n_layers_propagation: 1
activation: leaky_relu
concept_loss_weight: 0.5
normalize_concept_loss: false
prop_type: 'equations'
cat_latent: false