
_target_: "src.models.cbm.CBM"
hidden_size: 64
n_layers_concept_encoder: 2
n_layers_decoder: 1
activation: leaky_relu
concept_loss_weight: 0.5
normalize_concept_loss: false
decoder_type: mlp
dropout: 0.0