
_target_: "src.models.cem.CEM"
hidden_size: 64
concept_hidden_size: 8
n_layers_encoder: 1
n_layers_concept_encoder: 1
n_layers_decoder: 1
dropout: 0.0
activation: leaky_relu
concept_loss_weight: 0.5
normalize_concept_loss: false